name: Run Katalon Tests Every Tuesday

on:
  schedule:
    - cron: '*/6 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Katalon
        run: |
          curl -L -o katalon.tar.gz $(curl -s https://api.github.com/repos/katalon-studio/katalon-studio/releases/latest | jq -r '.assets[] | select(.name | contains("Linux_64")).browser_download_url')
          file katalon.tar.gz
          tar -xzf katalon.tar.gz
          sudo mv Katalon_Studio_Linux_64-* /opt/katalon

      - name: Run Katalon Tests
        run: |
          /opt/katalon/katalonc \
          -noSplash \
          -runMode=console \
          -projectPath="$(pwd)/Katalon Test/Test Automation.prj" \
          -retry=0 \
          -testSuitePath="Test Suites/HomePageTest" \
          -browserType="Chrome" \
          -apiKey="${{ secrets.KATALON_API_KEY  }}"

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: katalon-test-reports
          path: Reports/
