name: Run Katalon Tests Every Tuesday

on:
  schedule:
    - cron: '*/6 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Katalon
        run: |
          wget https://download.katalon.com/10.1.0/Katalon_Studio_Engine_Linux_64-10.1.0.tar.gz
          tar -xzf Katalon_Studio_Engine_Linux_64-10.1.0.tar.gz
          sudo mv Katalon_Studio_Engine_Linux_64-10.1.0 /opt/katalon

      -  name: Verify Katalon Installation
         run: ls -lh /opt/katalon

      - name: Run Katalon Tests
        run: |
          /opt/katalon/katalon \
          -noSplash \
          -runMode=console \
          -projectPath="$(pwd)/Katalon Test/Test Automation.prj" \
          -retry=0 \
          -testSuitePath="Test Suites/HomePageTest" \
          -browserType="Chrome" \
          -apiKey="${{ secrets.KATALON_API_KEY  }}"

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: katalon-test-reports
          path: Reports/
